name: string_to_letters_plugin
description: A new Flutter plugin that convert string to letters.
version: 0.0.2
homepage: https://github.com/Begato22/string_to_letters_plugin.git

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.string_to_letters_plugin
        pluginClass: StringToLettersPlugin
      ios:
        pluginClass: StringToLettersPlugin